### ISSUE TITLE
please put images to `.gitbook/assets` for the 4 new chapters

### ISSUE THREAD

**Issue by dongzhuoer** [lulab/teaching_book#9]
@james20141606 , as a convention, images should be put into `.gitbook/assets/`. Then you can link to them using relative path in `.md` (relative to the `.md` file).

Although your way works for GitBook, the book built by me fails, for example, figures in https://dongzhuoer.gitlab.io/lulab-teaching_book/python-tutorial.html are all broken. (But other chapters works find, like https://dongzhuoer.gitlab.io/lulab-teaching_book/kegg.html)

**Comment by lulab** [comment]
HI Zhuoer,

Thank you for your update. We no longer keep two books any more. Please
deprecate your version:  https://dongzhuoer.gitlab.io/lulab-teaching_book/
<https://dongzhuoer.gitlab.io/lulab-teaching_book/kegg.html>.

Therefore, I have added you back to the gitbook (
https://legacy.gitbook.com/book/lulab/teaching/details ). You can edit the
gitbook directly.

If small edits of others and all the edits of your own sections, you can
edit it directly without pulling request.
For large edits of other people, you may contact the author first to
confirm if they accept your suggestions or corrections.



Sincerely,
John

------
Zhi John Lu   |  鲁 志
MOE Key Lab of Bioinformatics
School of Life Sciences, Tsinghua University
Beijing 100084, China
http://ncrnalab.org/ <http://www.ncrnalab.org/>

**Comment by dongzhuoer** [comment]
Thanks for your trust. I will try my best to avoid conflict and respect other's opinions.
